# https://docs.travis-ci.com/user/precise-to-trusty-migration-guide/
dist: trusty

# See: https://github.com/travis-ci/travis-ci/issues/7019
sudo: required

language: java

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

os:
  - linux

env:
  matrix:
    - jdk_id=openjdk7
    - jdk_id=oraclejdk7
    - jdk_id=oraclejdk8
    - jdk_id=oraclejdk9

before_install:
  - hostname #workaround for https://github.com/travis-ci/travis-ci/issues/5227
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - hostname
  - cat /etc/hosts # optionally check the content *after*

script:
  - echo ${jdk_id} && jdk_switcher use ${jdk_id} && java -version && echo "Java home is set to ${JAVA_HOME}" && mvn test
